Update prepare

diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [ -z "$1" ] || [ -z "$2" ]; then
+  echo "Error: Missing required argument(s)."
+  exit 1
+fi
+
 gpg --full-gen-key
 pass init $1
 
